### PR TITLE
Adding unit test and fixing gradients for new interp op

### PR DESCRIPTION
**Pull request by dfm**
Here's an update to the new interp op where the gradients are now correct. It doesn't want to merge since you reverted the previous change, but you should try it out and see if it works for you. The test you sent me in #68 seems to be fine now.

### CODE REVIEW

**Comment by dfm** [comment]
Ok - I think I fixed the merge conflicts. Give it a shot and let me know!

**Comment by megbedell** [comment]
Thanks, this is working now - although I'm not sure that it speeds up performance noticeably vs. the old version of interp. Do you see improvement on your machine?

**Comment by megbedell** [comment]
nvm actually it is faster! thanks @dfm!!! you da 💣

**Comment by dfm** [comment]
Awesome!!

**Comment by davidwhogg** [comment]
Sick!!

**Pull request merged**
